GET http://127.0.0.1:8080/index.css HTTP/1.1

###

GET http://127.0.0.1:8080/v1/getAllUsers HTTP/1.1 ###
###
GET http://127.0.0.1:8080/v1/getUser?id=riley.smith@scu.edu HTTP/1.1

###

GET http://127.0.0.1:8080/v1/getProject?id=P1001 HTTP/1.1
###

POST http://127.0.0.1:8080/v1/updateProject HTTP/1.1
Content-Type: application/json


### GET
GET http://127.0.0.1:8080/v1/getLogin?email=mark.brown@scu.edu&password=mb12345 HTTP/1.1

### GET
GET http://127.0.0.1:8080/v1/getInterestedUsers?id=P1002

### GET
GET http://127.0.0.1:8080/v1/getInterestedProjects

###

POST http://127.0.0.1:8080/v1/setProjectInterest HTTP/1.1
Content-Type: application/json

{
"id":"P1002",
"setInterestTo":"true"
}

###

POST http://127.0.0.1:8080/v1/createSkill HTTP/1.1
Content-Type: application/json

{
"name":"C/C++",
"type":"cs"
}

### GET
GET http://127.0.0.1:8080/v1/getProjectsCreated?id=alice.smith@scu.edu

### GET
GET http://127.0.0.1:8080/v1/getSkills

POST http://127.0.0.1:8080/v1/createUser 
Content-Type: application/json

{
"Email":"alice.smith@scu.edu", 
"FirstName": "Alice", 
"LastName": "Smith", 
"Password": "as12345", 
"Skills": ["Web Development", "JavaScript", "React"], 
"Description": "Junior year student with a passion for front-end development.", 
"Year": "Junior", 
"Major": "Software Engineering", 
"ProjectIDs": ["P1002"]
}

###

POST http://127.0.0.1:8080/v1/updateUser 
Content-Type: application/json

{
"Email":"riley.smith@scu.edu", 
"Description":"Junior year student that likes to"
}

//TEST EXPRESS SESSIONS
//WHY? So client does not have to send sensitive credentials each time they login

### 1. LOGIN USER
GET http://127.0.0.1:8080/v1/getLogin?email=test@scu.edu&password=12345 HTTP/1.1

### 2. Validate the users' session was stored server side to get back their user object
GET http://127.0.0.1:8080/v1/getMyInfo